import { db } from "./client.js";
import { products, categories } from "./schema.js";
import { eq } from "drizzle-orm";

async function ensureCategoryPath(
  parentName,
  parentSlug,
  childName,
  childSlug
) {
  // find/create parent
  let parent = (await db.select().from(categories)).find(
    (c) => c.slug === parentSlug
  );
  if (!parent) {
    const r = await db
      .insert(categories)
      .values({ name: parentName, slug: parentSlug, parentId: null });
    parent = {
      id: r.insertId,
      name: parentName,
      slug: parentSlug,
      parentId: null,
    };
  }
  // find/create child
  let child = (await db.select().from(categories)).find(
    (c) => c.slug === childSlug
  );
  if (!child) {
    const r = await db
      .insert(categories)
      .values({ name: childName, slug: childSlug, parentId: parent.id });
    child = {
      id: r.insertId,
      name: childName,
      slug: childSlug,
      parentId: parent.id,
    };
  } else if (!child.parentId || child.parentId !== parent.id) {
    // Ensure existing child is linked to correct parent
    await db
      .update(categories)
      .set({ parentId: parent.id })
      .where(eq(categories.id, child.id));
    child.parentId = parent.id;
  }
  return child.id;
}

async function main() {
  // Clear existing rows (optional). Comment out if you don't want to truncate.
  // await db.delete(products);

  // Ensure categories exist and get Laptops categoryId
  const laptopsCategoryId = await ensureCategoryPath(
    "Electronics",
    "electronics",
    "Laptops",
    "electronics/laptops"
  );

  await db.insert(products).values([
    {
      categoryId: laptopsCategoryId,
      title: "Dell Latitude 7400",
      brand: "Dell",
      model: "Latitude 7400",
      sku: "DEL-L7400-i5-16-512",
      cpu: "Intel Core i5-8365U",
      gpu: "Intel UHD 620",
      ramGb: 16,
      storage: "512GB SSD NVMe",
      displaySizeInches: "14.0",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 300,
      condition: "Refurbished-A",
      cosmeticNotes: "Minor hairline marks on lid",
      functionalNotes: "Fully tested, no issues",
      batteryHealthPct: 88,
      batteryCycles: 220,
      ports: "2x USB-A, 2x USB-C TB3, HDMI, uSD, Audio",
      os: "Windows 11 Pro",
      keyboardLayout: "EN-IN",
      color: "Silver",
      weightKg: "1.35",
      dimensionsMm: "321 x 214 x 17",
      mrp: "64999.00",
      price: "45999.00",
      discountPercent: 29,
      gstPercent: 18,
      inStock: true,
      stockQty: 12,
      warrantyMonths: 6,
      returnWindowDays: 7,
      fulfillmentLocation: "Delhi",
      highlights: '14" FHD IPS\nThunderbolt 3\nBacklit keyboard',
      description: "Slim, business-grade ultrabook with great battery life.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "Lenovo ThinkPad T480",
      brand: "Lenovo",
      model: "ThinkPad T480",
      sku: "LEN-T480-i5-16-256",
      cpu: "Intel Core i5-8350U",
      gpu: "Intel UHD 620",
      ramGb: 16,
      storage: "256GB SSD NVMe",
      displaySizeInches: "14.0",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 250,
      condition: "Refurbished-A",
      cosmeticNotes: "Excellent condition",
      functionalNotes: "Battery replaced",
      batteryHealthPct: 95,
      batteryCycles: 15,
      ports: "USB-C, 2x USB-A, HDMI, RJ45, SD, Audio",
      os: "Windows 11 Pro",
      keyboardLayout: "EN-IN",
      color: "Black",
      weightKg: "1.65",
      dimensionsMm: "336 x 232 x 20",
      mrp: "57999.00",
      price: "39999.00",
      discountPercent: 31,
      gstPercent: 18,
      inStock: true,
      stockQty: 9,
      warrantyMonths: 6,
      returnWindowDays: 7,
      fulfillmentLocation: "Mumbai",
      highlights: "ThinkPad durability\nRJ45 Ethernet\nGreat keyboard",
      description: "Durable classic with hot-swappable battery support.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "HP EliteBook 840 G5",
      brand: "HP",
      model: "EliteBook 840 G5",
      sku: "HP-840G5-i5-16-512",
      cpu: "Intel Core i5-8350U",
      gpu: "Intel UHD 620",
      ramGb: 16,
      storage: "512GB SSD NVMe",
      displaySizeInches: "14.0",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 300,
      condition: "Refurbished-A",
      cosmeticNotes: "Top cover minor scuffs",
      functionalNotes: "No functional issues",
      batteryHealthPct: 90,
      batteryCycles: 120,
      ports: "USB-C, 2x USB-A, HDMI, Dock, Audio",
      os: "Windows 11 Pro",
      keyboardLayout: "EN-IN",
      color: "Silver",
      weightKg: "1.48",
      dimensionsMm: "326 x 234 x 18",
      mrp: "61999.00",
      price: "42999.00",
      discountPercent: 31,
      gstPercent: 18,
      inStock: true,
      stockQty: 15,
      warrantyMonths: 6,
      returnWindowDays: 7,
      fulfillmentLocation: "Bengaluru",
      highlights: "Premium build\nBang & Olufsen audio\nBacklit keyboard",
      description: "Executive-class ultrabook with robust security features.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "Apple MacBook Pro 13 (2017)",
      brand: "Apple",
      model: "MacBook Pro 13 2017",
      sku: "APL-MBP13-2017-i5-8-256",
      cpu: "Intel Core i5 2.3GHz",
      gpu: "Intel Iris Plus 640",
      ramGb: 8,
      storage: "256GB SSD",
      displaySizeInches: "13.3",
      displayResolution: "2560x1600",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 500,
      condition: "Refurbished-B",
      cosmeticNotes: "Light keyboard shine",
      functionalNotes: "macOS reset, iCloud unlocked",
      batteryHealthPct: 85,
      batteryCycles: 320,
      ports: "2x Thunderbolt 3, Audio",
      os: "macOS Monterey",
      keyboardLayout: "EN-US",
      color: "Space Gray",
      weightKg: "1.37",
      dimensionsMm: "304 x 212 x 15",
      mrp: "89999.00",
      price: "49999.00",
      discountPercent: 44,
      gstPercent: 18,
      inStock: true,
      stockQty: 5,
      warrantyMonths: 3,
      returnWindowDays: 7,
      fulfillmentLocation: "Delhi",
      highlights: "Retina display\nAll-day battery\nmacOS ecosystem",
      description: "Reliable Apple laptop for creators and students.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "Acer Aspire 5",
      brand: "Acer",
      model: "Aspire 5 A515",
      sku: "ACR-A515-R5-8-512",
      cpu: "AMD Ryzen 5 3500U",
      gpu: "Radeon Vega 8",
      ramGb: 8,
      storage: "512GB SSD",
      displaySizeInches: "15.6",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 250,
      condition: "Used",
      cosmeticNotes: "Normal usage marks",
      functionalNotes: "Clean install",
      batteryHealthPct: 78,
      batteryCycles: 420,
      ports: "USB-C, 2x USB-A, HDMI, RJ45, Audio",
      os: "Windows 10 Home",
      keyboardLayout: "EN-IN",
      color: "Blue",
      weightKg: "1.80",
      dimensionsMm: "363 x 247 x 18",
      mrp: "44999.00",
      price: "28999.00",
      discountPercent: 36,
      gstPercent: 18,
      inStock: true,
      stockQty: 7,
      warrantyMonths: 0,
      returnWindowDays: 7,
      fulfillmentLocation: "Pune",
      highlights: "Ryzen 5 performance\nFHD screen\nEveryday laptop",
      description: "Balanced performance for office and study.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "Dell XPS 13 (9370)",
      brand: "Dell",
      model: "XPS 13 9370",
      sku: "DEL-XPS9370-i7-16-512",
      cpu: "Intel Core i7-8550U",
      gpu: "Intel UHD 620",
      ramGb: 16,
      storage: "512GB SSD NVMe",
      displaySizeInches: "13.3",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 400,
      condition: "Refurbished-A",
      cosmeticNotes: "Very clean",
      functionalNotes: "All tests passed",
      batteryHealthPct: 87,
      batteryCycles: 260,
      ports: "2x TB3, 1x USB-C, uSD, Audio",
      os: "Windows 11 Pro",
      keyboardLayout: "EN-US",
      color: "Silver",
      weightKg: "1.21",
      dimensionsMm: "302 x 199 x 12",
      mrp: "109999.00",
      price: "63999.00",
      discountPercent: 42,
      gstPercent: 18,
      inStock: true,
      stockQty: 6,
      warrantyMonths: 6,
      returnWindowDays: 7,
      fulfillmentLocation: "Delhi",
      highlights: "InfinityEdge display\nPremium build\nLightweight",
      description: "High-end ultrabook with premium design.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "HP ProBook 440 G6",
      brand: "HP",
      model: "ProBook 440 G6",
      sku: "HP-440G6-i5-8-256",
      cpu: "Intel Core i5-8265U",
      gpu: "Intel UHD 620",
      ramGb: 8,
      storage: "256GB SSD",
      displaySizeInches: "14.0",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 250,
      condition: "Refurbished-B",
      cosmeticNotes: "Minor corner wear",
      functionalNotes: "Keyboard replaced",
      batteryHealthPct: 82,
      batteryCycles: 360,
      ports: "USB-C, 2x USB-A, HDMI, RJ45, Audio",
      os: "Windows 10 Pro",
      keyboardLayout: "EN-IN",
      color: "Silver",
      weightKg: "1.60",
      dimensionsMm: "324 x 238 x 18",
      mrp: "52999.00",
      price: "33999.00",
      discountPercent: 36,
      gstPercent: 18,
      inStock: true,
      stockQty: 10,
      warrantyMonths: 3,
      returnWindowDays: 7,
      fulfillmentLocation: "Jaipur",
      highlights: "Business-grade security\nComfortable typing",
      description: "Reliable business notebook for teams.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "Lenovo IdeaPad 3",
      brand: "Lenovo",
      model: "IdeaPad 3 15ADA",
      sku: "LEN-IP3-R3-8-512",
      cpu: "AMD Ryzen 3 3250U",
      gpu: "Radeon Vega 3",
      ramGb: 8,
      storage: "512GB SSD",
      displaySizeInches: "15.6",
      displayResolution: "1920x1080",
      displayPanel: "TN",
      displayRefreshHz: 60,
      brightnessNits: 220,
      condition: "Used",
      cosmeticNotes: "Visible wear on palmrest",
      functionalNotes: "No issues found",
      batteryHealthPct: 75,
      batteryCycles: 500,
      ports: "USB-C, 2x USB-A, HDMI, Audio",
      os: "Windows 10 Home",
      keyboardLayout: "EN-IN",
      color: "Platinum Grey",
      weightKg: "1.85",
      dimensionsMm: "362 x 253 x 20",
      mrp: "38999.00",
      price: "25999.00",
      discountPercent: 33,
      gstPercent: 18,
      inStock: true,
      stockQty: 11,
      warrantyMonths: 0,
      returnWindowDays: 7,
      fulfillmentLocation: "Lucknow",
      highlights: "Great value\nFull-size keyboard",
      description: "Budget work and study laptop.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "ASUS VivoBook 14",
      brand: "ASUS",
      model: "VivoBook X412",
      sku: "ASU-X412-i3-8-256",
      cpu: "Intel Core i3-10110U",
      gpu: "Intel UHD",
      ramGb: 8,
      storage: "256GB SSD",
      displaySizeInches: "14.0",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 220,
      condition: "Refurbished-B",
      cosmeticNotes: "Small dent on edge",
      functionalNotes: "Trackpad replaced",
      batteryHealthPct: 80,
      batteryCycles: 380,
      ports: "USB-C, 2x USB-A, HDMI, uSD, Audio",
      os: "Windows 11 Home",
      keyboardLayout: "EN-IN",
      color: "Slate Grey",
      weightKg: "1.45",
      dimensionsMm: "322 x 212 x 19",
      mrp: "40999.00",
      price: "27999.00",
      discountPercent: 32,
      gstPercent: 18,
      inStock: true,
      stockQty: 8,
      warrantyMonths: 3,
      returnWindowDays: 7,
      fulfillmentLocation: "Chandigarh",
      highlights: "ErgoLift hinge\nCompact design",
      description: "Portable everyday laptop with modern ports.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "MSI Modern 14",
      brand: "MSI",
      model: "Modern 14 B4MW",
      sku: "MSI-M14-R5-8-512",
      cpu: "AMD Ryzen 5 4500U",
      gpu: "Radeon Graphics",
      ramGb: 8,
      storage: "512GB SSD",
      displaySizeInches: "14.0",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 300,
      condition: "Refurbished-A",
      cosmeticNotes: "Like new",
      functionalNotes: "All tests OK",
      batteryHealthPct: 92,
      batteryCycles: 90,
      ports: "USB-C, 2x USB-A, HDMI, Audio",
      os: "Windows 11 Home",
      keyboardLayout: "EN-IN",
      color: "Carbon Gray",
      weightKg: "1.30",
      dimensionsMm: "319 x 220 x 16",
      mrp: "58999.00",
      price: "39999.00",
      discountPercent: 32,
      gstPercent: 18,
      inStock: true,
      stockQty: 4,
      warrantyMonths: 6,
      returnWindowDays: 7,
      fulfillmentLocation: "Hyderabad",
      highlights: "Ryzen 5 power\nThin & light",
      description: "Modern design with quiet performance.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "Lenovo ThinkPad X1 Carbon (6th Gen)",
      brand: "Lenovo",
      model: "X1 Carbon Gen 6",
      sku: "LEN-X1C6-i7-16-512",
      cpu: "Intel Core i7-8650U",
      gpu: "Intel UHD 620",
      ramGb: 16,
      storage: "512GB SSD NVMe",
      displaySizeInches: "14.0",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 400,
      condition: "Refurbished-A",
      cosmeticNotes: "Excellent",
      functionalNotes: "No issue",
      batteryHealthPct: 89,
      batteryCycles: 210,
      ports: "2x TB3, 2x USB-A, HDMI, Audio",
      os: "Windows 11 Pro",
      keyboardLayout: "EN-IN",
      color: "Black",
      weightKg: "1.13",
      dimensionsMm: "324 x 217 x 15",
      mrp: "119999.00",
      price: "69999.00",
      discountPercent: 42,
      gstPercent: 18,
      inStock: true,
      stockQty: 3,
      warrantyMonths: 6,
      returnWindowDays: 10,
      fulfillmentLocation: "Delhi",
      highlights: "Ultra lightweight\nLegendary keyboard",
      description: "Iconic ThinkPad with premium mobility.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "HP ZBook 15 G3",
      brand: "HP",
      model: "ZBook 15 G3",
      sku: "HP-ZB15G3-i7-16-512-Quadro",
      cpu: "Intel Core i7-6820HQ",
      gpu: "NVIDIA Quadro M2000M",
      ramGb: 16,
      storage: "512GB SSD + 1TB HDD",
      displaySizeInches: "15.6",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 300,
      condition: "Refurbished-B",
      cosmeticNotes: "Some chassis wear",
      functionalNotes: "HDD replaced",
      batteryHealthPct: 80,
      batteryCycles: 410,
      ports: "TB3, USB-A, HDMI, RJ45, VGA, SD, Audio",
      os: "Windows 10 Pro",
      keyboardLayout: "EN-IN",
      color: "Black",
      weightKg: "2.60",
      dimensionsMm: "386 x 264 x 26",
      mrp: "129999.00",
      price: "61999.00",
      discountPercent: 52,
      gstPercent: 18,
      inStock: true,
      stockQty: 2,
      warrantyMonths: 3,
      returnWindowDays: 7,
      fulfillmentLocation: "Noida",
      highlights: "Workstation power\nQuadro graphics",
      description: "Mobile workstation for CAD and 3D.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "ASUS TUF Gaming A15",
      brand: "ASUS",
      model: "TUF A15",
      sku: "ASU-TUFA15-R7-16-512-1650",
      cpu: "AMD Ryzen 7 4800H",
      gpu: "NVIDIA GTX 1650",
      ramGb: 16,
      storage: "512GB SSD",
      displaySizeInches: "15.6",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 144,
      brightnessNits: 250,
      condition: "Used",
      cosmeticNotes: "Gaming wear on WASD keys",
      functionalNotes: "Thermal paste redone",
      batteryHealthPct: 76,
      batteryCycles: 480,
      ports: "USB-C, 2x USB-A, HDMI, RJ45, Audio",
      os: "Windows 11 Home",
      keyboardLayout: "EN-IN",
      color: "Black",
      weightKg: "2.20",
      dimensionsMm: "360 x 256 x 25",
      mrp: "89999.00",
      price: "54999.00",
      discountPercent: 39,
      gstPercent: 18,
      inStock: true,
      stockQty: 6,
      warrantyMonths: 0,
      returnWindowDays: 7,
      fulfillmentLocation: "Bengaluru",
      highlights: "144Hz panel\n8-core Ryzen\nTUF durability",
      description: "Affordable gaming powerhouse.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "Apple MacBook Air (2019)",
      brand: "Apple",
      model: "MacBook Air 2019",
      sku: "APL-MBA2019-i5-8-256",
      cpu: "Intel Core i5 1.6GHz",
      gpu: "Intel UHD 617",
      ramGb: 8,
      storage: "256GB SSD",
      displaySizeInches: "13.3",
      displayResolution: "2560x1600",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 400,
      condition: "Refurbished-A",
      cosmeticNotes: "Very clean",
      functionalNotes: "Keyboard serviced",
      batteryHealthPct: 86,
      batteryCycles: 290,
      ports: "2x TB3, Audio",
      os: "macOS Big Sur",
      keyboardLayout: "EN-US",
      color: "Gold",
      weightKg: "1.25",
      dimensionsMm: "304 x 212 x 15.6",
      mrp: "79999.00",
      price: "47999.00",
      discountPercent: 40,
      gstPercent: 18,
      inStock: true,
      stockQty: 4,
      warrantyMonths: 3,
      returnWindowDays: 7,
      fulfillmentLocation: "Delhi",
      highlights: "Retina display\nSilent operation",
      description: "Lightweight Mac for everyday use.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "Microsoft Surface Laptop 3",
      brand: "Microsoft",
      model: "Surface Laptop 3",
      sku: "MS-SL3-R5-8-256",
      cpu: "AMD Ryzen 5 3580U",
      gpu: "Radeon RX Vega 9",
      ramGb: 8,
      storage: "256GB SSD",
      displaySizeInches: "15.0",
      displayResolution: "2496x1664",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 400,
      condition: "Refurbished-A",
      cosmeticNotes: "Clean",
      functionalNotes: "All tests OK",
      batteryHealthPct: 88,
      batteryCycles: 210,
      ports: "USB-C, USB-A, Surface Connect, Audio",
      os: "Windows 11 Home",
      keyboardLayout: "EN-US",
      color: "Platinum",
      weightKg: "1.54",
      dimensionsMm: "339 x 244 x 14.7",
      mrp: "99999.00",
      price: "61999.00",
      discountPercent: 38,
      gstPercent: 18,
      inStock: true,
      stockQty: 3,
      warrantyMonths: 6,
      returnWindowDays: 7,
      fulfillmentLocation: "Gurgaon",
      highlights: "3:2 display\nPremium build",
      description: "Beautiful display for productivity.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "Lenovo ThinkPad L490",
      brand: "Lenovo",
      model: "ThinkPad L490",
      sku: "LEN-L490-i5-16-512",
      cpu: "Intel Core i5-8265U",
      gpu: "Intel UHD 620",
      ramGb: 16,
      storage: "512GB SSD",
      displaySizeInches: "14.0",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 250,
      condition: "Refurbished-A",
      cosmeticNotes: "Very good",
      functionalNotes: "Battery new",
      batteryHealthPct: 96,
      batteryCycles: 10,
      ports: "USB-C, 2x USB-A, HDMI, RJ45, Audio",
      os: "Windows 11 Pro",
      keyboardLayout: "EN-IN",
      color: "Black",
      weightKg: "1.70",
      dimensionsMm: "335 x 235 x 23",
      mrp: "56999.00",
      price: "38999.00",
      discountPercent: 32,
      gstPercent: 18,
      inStock: true,
      stockQty: 9,
      warrantyMonths: 6,
      returnWindowDays: 7,
      fulfillmentLocation: "Kolkata",
      highlights: "Solid build\nGreat keyboard",
      description: "Reliable ThinkPad for professionals.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "HP EliteBook 830 G6",
      brand: "HP",
      model: "EliteBook 830 G6",
      sku: "HP-830G6-i5-16-256",
      cpu: "Intel Core i5-8365U",
      gpu: "Intel UHD 620",
      ramGb: 16,
      storage: "256GB SSD",
      displaySizeInches: "13.3",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 300,
      condition: "Refurbished-A",
      cosmeticNotes: "Excellent",
      functionalNotes: "All good",
      batteryHealthPct: 90,
      batteryCycles: 200,
      ports: "2x USB-A, USB-C, HDMI, Audio",
      os: "Windows 11 Pro",
      keyboardLayout: "EN-IN",
      color: "Silver",
      weightKg: "1.33",
      dimensionsMm: "308 x 230 x 17",
      mrp: "59999.00",
      price: "41999.00",
      discountPercent: 30,
      gstPercent: 18,
      inStock: true,
      stockQty: 6,
      warrantyMonths: 6,
      returnWindowDays: 7,
      fulfillmentLocation: "Ahmedabad",
      highlights: "Compact business laptop\nBacklit keys",
      description: "Travel-friendly business ultrabook.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "Dell Latitude 5490",
      brand: "Dell",
      model: "Latitude 5490",
      sku: "DEL-5490-i5-8-256",
      cpu: "Intel Core i5-8350U",
      gpu: "Intel UHD 620",
      ramGb: 8,
      storage: "256GB SSD",
      displaySizeInches: "14.0",
      displayResolution: "1366x768",
      displayPanel: "TN",
      displayRefreshHz: 60,
      brightnessNits: 220,
      condition: "Refurbished-B",
      cosmeticNotes: "Keyboard shine",
      functionalNotes: "New SSD",
      batteryHealthPct: 81,
      batteryCycles: 410,
      ports: "USB-C, 2x USB-A, HDMI, RJ45, VGA, Audio",
      os: "Windows 10 Pro",
      keyboardLayout: "EN-IN",
      color: "Black",
      weightKg: "1.60",
      dimensionsMm: "334 x 232 x 21",
      mrp: "45999.00",
      price: "29999.00",
      discountPercent: 35,
      gstPercent: 18,
      inStock: true,
      stockQty: 10,
      warrantyMonths: 3,
      returnWindowDays: 7,
      fulfillmentLocation: "Delhi",
      highlights: "Great value business laptop",
      description: "Dependable Latitude series for teams.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "Acer Nitro 5 (2019)",
      brand: "Acer",
      model: "Nitro 5 AN515",
      sku: "ACR-AN515-i5-8-256-1650",
      cpu: "Intel Core i5-9300H",
      gpu: "NVIDIA GTX 1650",
      ramGb: 8,
      storage: "256GB SSD + 1TB HDD",
      displaySizeInches: "15.6",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 120,
      brightnessNits: 250,
      condition: "Used",
      cosmeticNotes: "Edge wear",
      functionalNotes: "Fans cleaned",
      batteryHealthPct: 70,
      batteryCycles: 600,
      ports: "USB-C, 2x USB-A, HDMI, RJ45, Audio",
      os: "Windows 10 Home",
      keyboardLayout: "EN-IN",
      color: "Black",
      weightKg: "2.30",
      dimensionsMm: "363 x 255 x 26",
      mrp: "79999.00",
      price: "46999.00",
      discountPercent: 41,
      gstPercent: 18,
      inStock: true,
      stockQty: 5,
      warrantyMonths: 0,
      returnWindowDays: 7,
      fulfillmentLocation: "Nagpur",
      highlights: "120Hz display\nGTX graphics",
      description: "Gaming on a budget.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "HP Pavilion 15",
      brand: "HP",
      model: "Pavilion 15",
      sku: "HP-PAV15-R5-8-512",
      cpu: "AMD Ryzen 5 4500U",
      gpu: "Radeon Graphics",
      ramGb: 8,
      storage: "512GB SSD",
      displaySizeInches: "15.6",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 250,
      condition: "Refurbished-A",
      cosmeticNotes: "Very clean",
      functionalNotes: "Fresh OS",
      batteryHealthPct: 90,
      batteryCycles: 150,
      ports: "USB-C, 2x USB-A, HDMI, Audio",
      os: "Windows 11 Home",
      keyboardLayout: "EN-IN",
      color: "Silver",
      weightKg: "1.75",
      dimensionsMm: "360 x 235 x 18",
      mrp: "56999.00",
      price: "37999.00",
      discountPercent: 33,
      gstPercent: 18,
      inStock: true,
      stockQty: 7,
      warrantyMonths: 6,
      returnWindowDays: 7,
      fulfillmentLocation: "Indore",
      highlights: "Ryzen 5 performance\nFHD display",
      description: "Balanced thin-and-light.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "Lenovo Legion Y540",
      brand: "Lenovo",
      model: "Legion Y540",
      sku: "LEN-Y540-i7-16-256-1660Ti",
      cpu: "Intel Core i7-9750H",
      gpu: "NVIDIA GTX 1660 Ti",
      ramGb: 16,
      storage: "256GB SSD + 1TB HDD",
      displaySizeInches: "15.6",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 144,
      brightnessNits: 300,
      condition: "Used",
      cosmeticNotes: "Worn keycaps",
      functionalNotes: "Thermals optimized",
      batteryHealthPct: 72,
      batteryCycles: 650,
      ports: "USB-C, 3x USB-A, HDMI, RJ45, MiniDP, Audio",
      os: "Windows 10 Home",
      keyboardLayout: "EN-IN",
      color: "Black",
      weightKg: "2.30",
      dimensionsMm: "365 x 260 x 25",
      mrp: "109999.00",
      price: "69999.00",
      discountPercent: 36,
      gstPercent: 18,
      inStock: true,
      stockQty: 3,
      warrantyMonths: 0,
      returnWindowDays: 7,
      fulfillmentLocation: "Ahmedabad",
      highlights: "144Hz gaming\nStrong cooling",
      description: "Mid-range gaming laptop.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "Dell Latitude 7410",
      brand: "Dell",
      model: "Latitude 7410",
      sku: "DEL-7410-i7-16-512",
      cpu: "Intel Core i7-10610U",
      gpu: "Intel UHD",
      ramGb: 16,
      storage: "512GB SSD NVMe",
      displaySizeInches: "14.0",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 400,
      condition: "Refurbished-A",
      cosmeticNotes: "Excellent",
      functionalNotes: "All good",
      batteryHealthPct: 93,
      batteryCycles: 120,
      ports: "2x TB3, 2x USB-A, HDMI, uSD, Audio",
      os: "Windows 11 Pro",
      keyboardLayout: "EN-IN",
      color: "Grey",
      weightKg: "1.40",
      dimensionsMm: "321 x 212 x 18",
      mrp: "124999.00",
      price: "79999.00",
      discountPercent: 36,
      gstPercent: 18,
      inStock: true,
      stockQty: 4,
      warrantyMonths: 6,
      returnWindowDays: 10,
      fulfillmentLocation: "Delhi",
      highlights: "Premium Latitude\nLong battery",
      description: "Executive business ultrabook.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "HP Elite Dragonfly G1",
      brand: "HP",
      model: "Elite Dragonfly G1",
      sku: "HP-DRGNFLY-i5-16-512",
      cpu: "Intel Core i5-8265U",
      gpu: "Intel UHD 620",
      ramGb: 16,
      storage: "512GB SSD",
      displaySizeInches: "13.3",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 400,
      condition: "Refurbished-A",
      cosmeticNotes: "Grade A",
      functionalNotes: "All checks OK",
      batteryHealthPct: 91,
      batteryCycles: 140,
      ports: "2x TB3, USB-A, HDMI, Audio",
      os: "Windows 11 Pro",
      keyboardLayout: "EN-IN",
      color: "Blue",
      weightKg: "0.99",
      dimensionsMm: "304 x 197 x 16",
      mrp: "139999.00",
      price: "89999.00",
      discountPercent: 36,
      gstPercent: 18,
      inStock: true,
      stockQty: 2,
      warrantyMonths: 6,
      returnWindowDays: 10,
      fulfillmentLocation: "Mumbai",
      highlights: "Sub-1kg weight\nPremium build",
      description: "Ultra-light premium business convertible.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "ASUS ROG Zephyrus G14 (2020)",
      brand: "ASUS",
      model: "ROG G14 GA401",
      sku: "ASU-G14-R7-16-512-2060",
      cpu: "AMD Ryzen 7 4800HS",
      gpu: "NVIDIA RTX 2060 Max-Q",
      ramGb: 16,
      storage: "512GB SSD",
      displaySizeInches: "14.0",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 120,
      brightnessNits: 300,
      condition: "Used",
      cosmeticNotes: "Normal wear",
      functionalNotes: "Thermals serviced",
      batteryHealthPct: 79,
      batteryCycles: 500,
      ports: "USB-C, 2x USB-A, HDMI, Audio",
      os: "Windows 11 Home",
      keyboardLayout: "EN-US",
      color: "White",
      weightKg: "1.60",
      dimensionsMm: "324 x 220 x 18",
      mrp: "134999.00",
      price: "89999.00",
      discountPercent: 33,
      gstPercent: 18,
      inStock: true,
      stockQty: 3,
      warrantyMonths: 0,
      returnWindowDays: 7,
      fulfillmentLocation: "Bengaluru",
      highlights: "120Hz gaming\nCompact powerhouse",
      description: "Beloved compact gaming laptop.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "Microsoft Surface Pro 6",
      brand: "Microsoft",
      model: "Surface Pro 6",
      sku: "MS-SP6-i5-8-256",
      cpu: "Intel Core i5-8250U",
      gpu: "Intel UHD 620",
      ramGb: 8,
      storage: "256GB SSD",
      displaySizeInches: "12.3",
      displayResolution: "2736x1824",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 400,
      condition: "Refurbished-A",
      cosmeticNotes: "Very clean",
      functionalNotes: "Battery good",
      batteryHealthPct: 90,
      batteryCycles: 180,
      ports: "USB-A, MiniDP, Surface Connect, Audio",
      os: "Windows 11 Home",
      keyboardLayout: "EN-US",
      color: "Black",
      weightKg: "0.78",
      dimensionsMm: "292 x 201 x 8.5",
      mrp: "79999.00",
      price: "48999.00",
      discountPercent: 39,
      gstPercent: 18,
      inStock: true,
      stockQty: 5,
      warrantyMonths: 3,
      returnWindowDays: 7,
      fulfillmentLocation: "Delhi",
      highlights: "2-in-1 versatility\nHigh-res display",
      description: "Tablet-laptop hybrid for mobility.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "Lenovo ThinkBook 14",
      brand: "Lenovo",
      model: "ThinkBook 14",
      sku: "LEN-TB14-i5-8-512",
      cpu: "Intel Core i5-10210U",
      gpu: "Intel UHD",
      ramGb: 8,
      storage: "512GB SSD",
      displaySizeInches: "14.0",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 250,
      condition: "Refurbished-A",
      cosmeticNotes: "Excellent",
      functionalNotes: "All OK",
      batteryHealthPct: 92,
      batteryCycles: 140,
      ports: "USB-C, 2x USB-A, HDMI, RJ45, Audio",
      os: "Windows 11 Pro",
      keyboardLayout: "EN-IN",
      color: "Mineral Grey",
      weightKg: "1.50",
      dimensionsMm: "323 x 218 x 17.9",
      mrp: "62999.00",
      price: "41999.00",
      discountPercent: 33,
      gstPercent: 18,
      inStock: true,
      stockQty: 8,
      warrantyMonths: 6,
      returnWindowDays: 7,
      fulfillmentLocation: "Pune",
      highlights: "Business features\nSolid build",
      description: "Modern business laptop with USB-C.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "Acer Swift 3",
      brand: "Acer",
      model: "Swift 3 SF314",
      sku: "ACR-SF314-R5-8-512",
      cpu: "AMD Ryzen 5 4500U",
      gpu: "Radeon Graphics",
      ramGb: 8,
      storage: "512GB SSD",
      displaySizeInches: "14.0",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 300,
      condition: "Refurbished-A",
      cosmeticNotes: "Like new",
      functionalNotes: "No issues",
      batteryHealthPct: 94,
      batteryCycles: 80,
      ports: "USB-C, 2x USB-A, HDMI, Audio",
      os: "Windows 11 Home",
      keyboardLayout: "EN-IN",
      color: "Silver",
      weightKg: "1.20",
      dimensionsMm: "319 x 210 x 16",
      mrp: "59999.00",
      price: "40999.00",
      discountPercent: 32,
      gstPercent: 18,
      inStock: true,
      stockQty: 9,
      warrantyMonths: 6,
      returnWindowDays: 7,
      fulfillmentLocation: "Delhi",
      highlights: "Lightweight\nLong battery",
      description: "Great balance of portability and power.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "MSI GF63 Thin",
      brand: "MSI",
      model: "GF63 9SC",
      sku: "MSI-GF63-i5-8-512-1650MaxQ",
      cpu: "Intel Core i5-9300H",
      gpu: "NVIDIA GTX 1650 Max-Q",
      ramGb: 8,
      storage: "512GB SSD",
      displaySizeInches: "15.6",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 250,
      condition: "Refurbished-B",
      cosmeticNotes: "Scratches on lid",
      functionalNotes: "Thermals serviced",
      batteryHealthPct: 73,
      batteryCycles: 520,
      ports: "USB-C, 3x USB-A, HDMI, RJ45, Audio",
      os: "Windows 10 Home",
      keyboardLayout: "EN-IN",
      color: "Black",
      weightKg: "1.86",
      dimensionsMm: "359 x 254 x 21.7",
      mrp: "74999.00",
      price: "48999.00",
      discountPercent: 35,
      gstPercent: 18,
      inStock: true,
      stockQty: 4,
      warrantyMonths: 0,
      returnWindowDays: 7,
      fulfillmentLocation: "Jaipur",
      highlights: "Thin chassis\nGTX gaming",
      description: "Entry-level gaming machine.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "Apple MacBook Pro 15 (2018)",
      brand: "Apple",
      model: "MacBook Pro 15 2018",
      sku: "APL-MBP15-2018-i7-16-512-R560X",
      cpu: "Intel Core i7 2.6GHz",
      gpu: "Radeon Pro 560X",
      ramGb: 16,
      storage: "512GB SSD",
      displaySizeInches: "15.4",
      displayResolution: "2880x1800",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 500,
      condition: "Refurbished-B",
      cosmeticNotes: "Light wear",
      functionalNotes: "macOS reset",
      batteryHealthPct: 82,
      batteryCycles: 380,
      ports: "4x TB3, Audio",
      os: "macOS Monterey",
      keyboardLayout: "EN-US",
      color: "Space Gray",
      weightKg: "1.83",
      dimensionsMm: "349 x 240 x 15.5",
      mrp: "179999.00",
      price: "109999.00",
      discountPercent: 39,
      gstPercent: 18,
      inStock: true,
      stockQty: 2,
      warrantyMonths: 3,
      returnWindowDays: 7,
      fulfillmentLocation: "Mumbai",
      highlights: "Retina 15\nPro graphics",
      description: "Powerful Mac for creators.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "Dell Inspiron 7490",
      brand: "Dell",
      model: "Inspiron 7490",
      sku: "DEL-7490-i5-8-512",
      cpu: "Intel Core i5-10210U",
      gpu: "Intel UHD",
      ramGb: 8,
      storage: "512GB SSD",
      displaySizeInches: "14.0",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 300,
      condition: "Refurbished-A",
      cosmeticNotes: "Excellent",
      functionalNotes: "All OK",
      batteryHealthPct: 92,
      batteryCycles: 150,
      ports: "USB-C, 2x USB-A, HDMI, Audio",
      os: "Windows 11 Home",
      keyboardLayout: "EN-IN",
      color: "Silver",
      weightKg: "1.40",
      dimensionsMm: "321 x 214 x 17",
      mrp: "74999.00",
      price: "51999.00",
      discountPercent: 31,
      gstPercent: 18,
      inStock: true,
      stockQty: 5,
      warrantyMonths: 6,
      returnWindowDays: 7,
      fulfillmentLocation: "Delhi",
      highlights: "Lightweight aluminum\nGood battery",
      description: "Premium portability for office users.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "HP Omen 15 (2019)",
      brand: "HP",
      model: "Omen 15 2019",
      sku: "HP-OM15-i7-16-512-2060",
      cpu: "Intel Core i7-9750H",
      gpu: "NVIDIA RTX 2060",
      ramGb: 16,
      storage: "512GB SSD",
      displaySizeInches: "15.6",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 144,
      brightnessNits: 300,
      condition: "Used",
      cosmeticNotes: "Gaming wear",
      functionalNotes: "Fans cleaned",
      batteryHealthPct: 74,
      batteryCycles: 700,
      ports: "USB-C, 3x USB-A, HDMI, RJ45, MiniDP, SD, Audio",
      os: "Windows 11 Home",
      keyboardLayout: "EN-IN",
      color: "Black",
      weightKg: "2.30",
      dimensionsMm: "360 x 264 x 25",
      mrp: "139999.00",
      price: "94999.00",
      discountPercent: 32,
      gstPercent: 18,
      inStock: true,
      stockQty: 2,
      warrantyMonths: 0,
      returnWindowDays: 7,
      fulfillmentLocation: "Chennai",
      highlights: "144Hz gaming\nRTX graphics",
      description: "Performance gaming laptop with RTX.",
    },
    {
      categoryId: laptopsCategoryId,
      title: "ASUS ZenBook 14",
      brand: "ASUS",
      model: "ZenBook 14 UX433",
      sku: "ASU-UX433-i7-16-512",
      cpu: "Intel Core i7-8565U",
      gpu: "Intel UHD 620",
      ramGb: 16,
      storage: "512GB SSD",
      displaySizeInches: "14.0",
      displayResolution: "1920x1080",
      displayPanel: "IPS",
      displayRefreshHz: 60,
      brightnessNits: 300,
      condition: "Refurbished-A",
      cosmeticNotes: "Excellent",
      functionalNotes: "All good",
      batteryHealthPct: 90,
      batteryCycles: 200,
      ports: "USB-C, 2x USB-A, HDMI, uSD, Audio",
      os: "Windows 11 Home",
      keyboardLayout: "EN-IN",
      color: "Royal Blue",
      weightKg: "1.19",
      dimensionsMm: "319 x 199 x 15.9",
      mrp: "89999.00",
      price: "61999.00",
      discountPercent: 31,
      gstPercent: 18,
      inStock: true,
      stockQty: 3,
      warrantyMonths: 6,
      returnWindowDays: 7,
      fulfillmentLocation: "Delhi",
      highlights: "NanoEdge bezels\nPremium design",
      description: "Compact premium ultrabook.",
    },
  ]);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
